name: Documentation

on:
  push:
    branches:
      - master
    tags: "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.5"
      - name: Install dependencies
        env:
          PYTHON:
        run: julia --project=docs -e 'using Pkg; Pkg.add("Documenter"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          # For authentication with GitHub Actions token
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # # For authentication with SSH deploy key
          # DOCUMENTER_KEY: ${{secrets.DOCUMENTER_KEY}}
        run: julia --project=docs --color=yes docs/make.jl
